name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - voici>=0.2.0,<0.3.0
    - jupyterlite-xeus-python>=0.6.0,<0.7.0
    # TODO: remove when a new voici is available
    - jupyterlite==0.1.0b18
