name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlite-core =0.1.1
  - jupyterlite-xeus-python >=0.9.0,<0.10.0
  - pip:
    - voila==0.5.0a4
    - voici>=0.4.4,<0.5.0
