name: vg
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ipywidgets
  - plotly
  - shap
  - catboost
